# Template Name
## Subheading
#### Student Name: XXXX XXXX
#### Student ID: 000000

Environment: Python 3 and Jupyter notebook

## Introduction
You should give a brief information of this assessment task here.

## Importing libraries

In [1]:
import pandas as pd
import re

### Datasets:

DNA sequence prediction
- https://www.kaggle.com/datasets/harshvardhan21/dna-sequence-prediction/data 

Molecular Biology (Splice-junction Gene Sequences)
- https://archive.ics.uci.edu/dataset/69/molecular+biology+splice+junction+gene+sequences

In [2]:
DNA_seq = pd.read_csv('/Users/m/Documents/Uni/2026/Case Studies in Data Science /Sequence Analysis Comparison/Data/DNA_Seq/train.csv')
DNA_seq.head()

,Unnamed: 0,NCBIGeneID,Symbol,Description,GeneType,GeneGroupMethod,NucleotideSequence
0,0,106481178,RNU4-21P,"RNA, U4 small nuclear 21, pseudogene",PSEUDO,NCBI Ortholog,<AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAG...
1,1,123477792,LOC123477792,Sharpr-MPRA regulatory region 12926,BIOLOGICAL_REGION,NCBI Ortholog,<CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCG...
2,2,113174975,LOC113174975,Sharpr-MPRA regulatory region 7591,BIOLOGICAL_REGION,NCBI Ortholog,<TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTC...
3,3,116216107,LOC116216107,CRISPRi-validated cis-regulatory element chr10...,BIOLOGICAL_REGION,NCBI Ortholog,<CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGC...
4,4,28502,IGHD2-21,immunoglobulin heavy diversity 2-21,OTHER,NCBI Ortholog,<AGCATATTGTGGTGGTGACTGCTATTCC>

In [3]:
columns = ['Class', 'InstanceName', 'Sequence']
splice_seq = pd.read_csv('/Users/m/Documents/Uni/2026/Case Studies in Data Science /Sequence Analysis Comparison/Data/Splice_Seq/splice.data', names=columns)
splice_seq.head()

,Class,InstanceName,Sequence
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGG...
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGG...
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGG...
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGT...
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTG...

About splice junctions: 

'Splice junctions are points on a DNA sequence at which `superfluous' DNA is removed during the process of protein creation in higher organisms.  The problem posed in this dataset is to recognize, given a sequence of DNA, the boundaries between exons (the parts of the DNA sequence retained after splicing) and introns (the parts of the DNA sequence that are spliced out). This problem consists of two subtasks: recognizing exon/intron boundaries (referred to as EI sites), and recognizing intron/exon boundaries (IE sites). (In the biological community, IE borders are referred to a 'acceptors' while EI borders are referred to as 'donors'.)'


#### Next we do some data cleaning:

In [4]:
def ProcessingText(text):
    return re.sub(r'[^A-Za-z0-9\s]', '', text)

DNA_seq["NucleotideSequence"] = DNA_seq["NucleotideSequence"].apply(lambda text: ProcessingText(text))
#DNA_seq["NucleotideSequence"].loc[0, "NucleotideSequence"]
DNA_seq.head()

,Unnamed: 0,NCBIGeneID,Symbol,Description,GeneType,GeneGroupMethod,NucleotideSequence
0,0,106481178,RNU4-21P,"RNA, U4 small nuclear 21, pseudogene",PSEUDO,NCBI Ortholog,AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAGG...
1,1,123477792,LOC123477792,Sharpr-MPRA regulatory region 12926,BIOLOGICAL_REGION,NCBI Ortholog,CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCGA...
2,2,113174975,LOC113174975,Sharpr-MPRA regulatory region 7591,BIOLOGICAL_REGION,NCBI Ortholog,TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTCC...
3,3,116216107,LOC116216107,CRISPRi-validated cis-regulatory element chr10...,BIOLOGICAL_REGION,NCBI Ortholog,CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGCT...
4,4,28502,IGHD2-21,immunoglobulin heavy diversity 2-21,OTHER,NCBI Ortholog,AGCATATTGTGGTGGTGACTGCTATTCC

In [5]:
DNA_seq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22593 entries, 0 to 22592
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          22593 non-null  int64
 1   NCBIGeneID          22593 non-null  int64
 2   Symbol              22593 non-null  object
 3   Description         22593 non-null  object
 4   GeneType            22593 non-null  object
 5   GeneGroupMethod     22593 non-null  object
 6   NucleotideSequence  22593 non-null  object
dtypes: int64(2), object(5)
memory usage: 1.2+ MB

In [6]:
print(DNA_seq.isna().sum())
print(splice_seq.isna().sum())

Unnamed: 0            0
NCBIGeneID            0
Symbol                0
Description           0
GeneType              0
GeneGroupMethod       0
NucleotideSequence    0
dtype: int64
Class           0
InstanceName    0
Sequence        0
dtype: int64

In [7]:
# Visualising Distributions

## Task Name. What would we like to add?
Feature engineering

In [8]:
"""from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

X = DNA_seq['NucleotideSequence'].apply(list).apply(pd.Series)

X_train, X_test, Y_train, Y_test = train_test_split(
        X,  DNA_seq['GeneType'],
        test_size=0.33, random_state=0)

encoder= OneHotEncoder()
training = pd.DataFrame(encoder.fit_transform(X_train).toarray())
testing = pd.DataFrame(encoder.fit_transform(X_test).toarray())

training
"""

"from sklearn.preprocessing import OneHotEncoder\nfrom sklearn.model_selection import train_test_split\n\nX = DNA_seq['NucleotideSequence'].apply(list).apply(pd.Series)\n\nX_train, X_test, Y_train, Y_test = train_test_split(\n        X,  DNA_seq['GeneType'],\n        test_size=0.33, random_state=0)\n\nencoder= OneHotEncoder()\ntraining = pd.DataFrame(encoder.fit_transform(X_train).toarray())\ntesting = pd.DataFrame(encoder.fit_transform(X_test).toarray())\n\ntraining\n"

In [9]:
DNA_seq["SequenceLength"] = (
    DNA_seq["NucleotideSequence"]
    .astype(str)
    .str.len()
)

DNA_seq["SequenceLength"].describe()

DNA_seq["SequenceLength"] = (
    DNA_seq["NucleotideSequence"]
    .astype(str)
    .str.len()
)

DNA_seq["SequenceLength"].describe()

count    22593.000000
mean       359.724871
std        260.474730
min          2.000000
25%        120.000000
50%        295.000000
75%        518.000000
max       1000.000000
Name: SequenceLength, dtype: float64

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import random
import numpy as np

In [11]:
seed = 22
random.seed(22)
np.random.seed(22)
torch.manual_seed(22)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [12]:
X_DNA = DNA_seq["NucleotideSequence"]
Y_DNA = DNA_seq['GeneType']

label_encoder_DNA = LabelEncoder()
Y_DNA_encoded = label_encoder_DNA.fit_transform(Y_DNA)
print(label_encoder_DNA.classes_)

['BIOLOGICAL_REGION' 'OTHER' 'PROTEIN_CODING' 'PSEUDO' 'ncRNA' 'rRNA'
 'scRNA' 'snRNA' 'snoRNA' 'tRNA']

Do a visualisation of the frequencies??

^^ You can show the part above what it looks like in the slides!!

## $$Temporary fix bellow

In [13]:
#print(pd.Series(Y_temp_DNA).value_counts().sort_values())

In [14]:
# As can be seen above only a single observation is found for when Y_DNA_encoded == 6, a temporary workaround for this is to remove 6
mask = Y_DNA_encoded != 6

X_DNA_filtered = X_DNA.loc[mask].reset_index(drop=True)
Y_DNA_encoded = Y_DNA_encoded[mask]

what the solution is for:

In [15]:
# Splits the DNA data into 70% training (X_train_DNA) and 30% temporary.
X_train_DNA, X_temp_DNA, Y_train_DNA, Y_temp_DNA = train_test_split(X_DNA_filtered, Y_DNA_encoded, test_size=0.30, random_state=22,stratify=Y_DNA_encoded)

# Splits the temporary DNA data from the 30% in half resulting in 15% of data being available for validation and 15% for testing.
X_val_DNA, X_test_DNA, Y_val_DNA, Y_test_DNA = train_test_split(X_temp_DNA, Y_temp_DNA, test_size=0.50, random_state=22, stratify=Y_temp_DNA)

In [16]:
splice_seq

,Class,InstanceName,Sequence
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGG...
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGG...
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGG...
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGT...
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTG...
...,...,...,...
3185,N,ORAHBPSBD-NEG-2881,TCTCTTCCCTTCCCCTCTCTCTTTCTTTCTTTT...
3186,N,ORAINVOL-NEG-2161,GAGCTCCCAGAGCAGCAAGAGGGCCAGCTGAA...
3187,N,ORARGIT-NEG-241,TCTCGGGGGCGGCCGGCGCGGCGGGGAGCG...
3188,N,TARHBB-NEG-541,ATTCTACTTAGTAAACATAATTTCTTGTG...
3189,N,TARHBD-NEG-1981,AGGCTGCCTATCAGAAGGTGGTGGCTGGTG...

In [17]:
X_splice = splice_seq["Sequence"]
Y_splice = splice_seq["Class"]

label_encoder_splice = LabelEncoder()

Y_splice_encoded = label_encoder_splice.fit_transform(
    Y_splice
)

print(label_encoder_splice.classes_)

['EI' 'IE' 'N']

In [18]:
# Splits the splice data into 70% training (X_train_splice) and 30% temporary.
X_train_splice, X_temp_splice, Y_train_splice, Y_temp_splice = train_test_split(X_splice, Y_splice_encoded, test_size=0.30, random_state=22, stratify=Y_splice_encoded)

# Splits the temporary splice data from the 30% in half resulting in 15% of data being available for validation and 15% for testing.
X_val_splice, X_test_splice, Y_val_splice, Y_test_splice = train_test_split(X_temp_splice, Y_temp_splice, test_size=0.50, random_state=22, stratify=Y_temp_splice)

### Creating a CNN

Describe please c:

In [19]:
# Improving performance on my mac system
device = torch.device("mps" if torch.backends.mps.is_available() else 'cpu')

#https://docs.pytorch.org/docs/2.13/notes/mps.html

In [20]:
def one_hot_encode(sequence):
    mapping = {"A":0,'C':1,'G':2,'T':3}
    encoded = torch.zeros(4, len(sequence), dtype=torch.float32)

    for location, base in enumerate(sequence):
        if base in mapping:
            encoded[mapping[base], location] = 1
    return encoded

one_hot_encode('ACGTACGT')

tensor([[1., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 1.]])

In [21]:

class DNA_dataset(Dataset):
    def __init__(self, sequences, labels):
        self.sequences = pd.Series(sequences).reset_index(drop = True)
        self.labels = pd.Series(labels).reset_index(drop = True)

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, index): 
        sequence = one_hot_encode(self.sequences.iloc[index])
        label = torch.tensor(self.labels.iloc[index], dtype=torch.long)
        return sequence, label

# https://www.kaggle.com/code/jiazhuang/cnn-with-pytorch-for-beginners

In [22]:
# Initialising Pytorch Dataset for non-splicing dataset

train_dataset_DNA = DNA_dataset(X_train_DNA, Y_train_DNA)
val_dataset_DNA = DNA_dataset(X_val_DNA, Y_val_DNA)
test_dataset_DNA = DNA_dataset(X_test_DNA, Y_test_DNA)

# Initialising Pytorch Dataset for splicing dataset
train_dataset_splice = DNA_dataset(X_train_splice, Y_train_splice)
val_dataset_splice = DNA_dataset(X_val_splice, Y_val_splice)
test_dataset_splice = DNA_dataset(X_test_splice, Y_test_splice)

In [23]:
# The dataloaders (maybe move them somewhere else???) https://docs.pytorch.org/tutorials/beginner/basics/optimization_tutorial.html 
from torch.utils.data import DataLoader

generator = torch.Generator()
generator.manual_seed(22)

# DNA
train_loader_DNA = DataLoader(train_dataset_DNA, batch_size=1, shuffle=True, generator=generator)
val_loader_DNA = DataLoader(val_dataset_DNA,batch_size=1, shuffle=False, generator=generator)
test_loader_DNA = DataLoader(test_dataset_DNA, batch_size=1,shuffle=False, generator=generator)

# Splice
train_loader_splice = DataLoader(train_dataset_splice, batch_size=1, shuffle=True, generator=generator)
val_loader_splice = DataLoader(val_dataset_splice,batch_size=1, shuffle=False, generator=generator)
test_loader_splice = DataLoader(test_dataset_splice, batch_size=1, shuffle=False, generator=generator)

CNN class

In [24]:
class CNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.conv1 = nn.Conv1d(in_channels = 4, out_channels = 32,
                               padding = 0, kernel_size = 3)
        self.conv2 = nn.Conv1d(in_channels = 32, out_channels = 64,
                                       padding = 0, kernel_size = 2)
        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(64, num_classes)
    def forward(self, value):
        value = F.relu(self.conv1(value))
        value = F.relu(self.conv2(value))

        # Global pooling??
        value = torch.max(value, dim = 2).values

        value = self.dropout(value)
        value = self.fc(value)
        return value

In [25]:
# Creating the models themselves 

# DNA
num_classes_DNA = len(label_encoder_DNA.classes_)
model_DNA = CNN(num_classes=num_classes_DNA).to(device)

# Splice
num_classes_splice = len(label_encoder_splice.classes_)
model_splice = CNN(num_classes=num_classes_splice).to(device)

Loss function and optimiser

The optimiser chosen was Adam (Adaptive Moment Estimation) due to its advantages as a combination of Momentum and RMSProp optimiser algorithms, Adam is the most famous optimisation algorithm in deep learning and hence was chosen (https://towardsdatascience.com/understanding-deep-learning-optimizers-momentum-adagrad-rmsprop-adam-e311e377e9c2/)

In [26]:
# Starting loss function
loss_fn = nn.CrossEntropyLoss()

# Train loop
def train_loop(dataloader, model, loss_fn, optimizer, device):
    size = len(dataloader.dataset)
    # model set to training mode
    model.train()
    total_loss = 0.0
    for X, y in dataloader:
        # Move DNA sequence and Label to device
        X = X.to(device)
        y = y.to(device)

        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        

        total_loss += loss.item()
    # average training loss
    return (total_loss / len(dataloader))

# Test loop
def evaluate_loop(dataloader, model, loss_fn, device):
    # Set the model to evaluation mode
    model.eval()
    total_loss = 0.0
    y_true = []
    y_pred = []

    # The code below ensures that no gradients are computed during test mode
    with torch.no_grad():
        for X, y in dataloader:
            X = X.to(device)
            y = y.to(device)
            pred = model(X)
            total_loss += loss_fn(pred, y).item()
            # Predicted class
            predicted_class = pred.argmax(dim = 1)
            y_true.extend(y.cpu().numpy())
            y_pred.extend(predicted_class.cpu().numpy())

    average_loss = total_loss / len(dataloader)
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='macro')
    return average_loss, accuracy, f1 

# https://docs.pytorch.org/tutorials/beginner/basics/optimization_tutorial.html

Note for macro f1: 
computed using the unweighted mean of all the per-class F1 scores (https://towardsdatascience.com/micro-macro-weighted-averages-of-f1-score-clearly-explained-b603420b292f/). Which is chosen since we want all classes to be treated equally

# Dataset training

Tuning for best learning rate:

In [27]:
import copy
initial_model_state = copy.deepcopy(model_DNA.state_dict())

learning_rate = [0.0001, 0.001, 0.01]
best_f1_score = -1
best_learning_rate = 0

for lr in learning_rate:
    print(f"Testing learning rate: {lr}")

    # resettign CNN
    model_DNA.load_state_dict(initial_model_state)
    optimizer_DNA = torch.optim.Adam(model_DNA.parameters(), lr = lr)
    best_model_for_lr = -1

    for epoch in range(3):
        train_loss = train_loop(train_loader_DNA, model_DNA, loss_fn, optimizer_DNA, device)

        # Validate
        val_loss, val_accuracy, val_f1 = evaluate_loop(val_loader_DNA, model_DNA, loss_fn, device)
        print(f"\nEpoch {epoch}")
        print(f"Training Loss: {train_loss}\nValidation_loss: {val_loss}\
                \nAccuracy: {val_accuracy}\nMacro F1: {val_f1}\n")

        # Save the model if it has the best F1 score so far
        if val_f1 > best_f1_score: 
            best_model_for_lr = val_f1
    print(f"Best F1 score for learning rate {lr}: {best_model_for_lr}")
    if best_model_for_lr > best_f1_score:
        best_f1_score = best_model_for_lr
        best_learning_rate = lr

Testing learning rate: 0.0001

Epoch 0
Training Loss: 1.416202255870709
Validation_loss: 1.3272410436602664
Accuracy: 0.4654663518299882
Macro F1: 0.08145783993555418


Epoch 1
Training Loss: 1.2947640294344702
Validation_loss: 1.2356909342822668
Accuracy: 0.5174144037780402
Macro F1: 0.13531334259747452


Epoch 2
Training Loss: 1.2237201192034781
Validation_loss: 1.1757573062002025
Accuracy: 0.5687721369539551
Macro F1: 0.2813033403172964

Best F1 score for learning rate 0.0001: 0.2813033403172964
Testing learning rate: 0.001

Epoch 0
Training Loss: 1.2594499912524988
Validation_loss: 1.126963631677691
Accuracy: 0.5802833530106257
Macro F1: 0.3835673571537011


Epoch 1
Training Loss: 1.1608743869644116
Validation_loss: 1.1023015378630217
Accuracy: 0.5858913813459268
Macro F1: 0.38745587237735934


Epoch 2
Training Loss: 1.1449399697122882
Validation_loss: 1.1011992907580406
Accuracy: 0.5844155844155844
Macro F1: 0.41119321169323

Best F1 score for learning rate 0.001: 0.41119321169323
Testing learning rate: 0.01

Epoch 0
Training Loss: 1.3919926296227203
Validation_loss: 1.3523296689902737
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081


Epoch 1
Training Loss: 1.3968792661627774
Validation_loss: 1.4426005190983855
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081


Epoch 2
Training Loss: 1.4453261269116653
Validation_loss: 1.449712955825022
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Best F1 score for learning rate 0.01: -1

Further tuning with the best learning rate

In [28]:
best_f1_score = -1
best_epoch = 0
best_model_state = None

# Initializing Optimizer
optimizer_DNA = torch.optim.Adam(model_DNA.parameters(), lr = best_learning_rate) 

for epoch in range(10):
    train_loss = train_loop(train_loader_DNA, model_DNA, loss_fn, optimizer_DNA, device)

    # Validate
    val_loss, val_accuracy, val_f1 = evaluate_loop(
        val_loader_DNA, model_DNA, loss_fn, device
    )
    print(f"Epoch {epoch}\n")
    print(f"Training Loss: {train_loss}\nValidation_loss: {val_loss}\
            \nAccuracy: {val_accuracy}\nMacro F1: {val_f1}\n")

    # Save the model if it has the best F1 score so far
    if val_f1 > best_f1_score: 
        best_f1_score = val_f1
        best_epoch = epoch
        best_model_state = model_DNA.state_dict()

print(f"Best F1 score: {best_f1_score} at epoch {best_epoch}")
model_DNA.load_state_dict(best_model_state)

Epoch 0

Training Loss: 1.441560935606233
Validation_loss: 1.439851977837128
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 1

Training Loss: 1.4402794763846347
Validation_loss: 1.4395179376621876
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 2

Training Loss: 1.4402314339742213
Validation_loss: 1.4395352999779805
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 3

Training Loss: 1.4401249727058145
Validation_loss: 1.4397542752334331
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 4

Training Loss: 1.4402905159202237
Validation_loss: 1.4394795139360879
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 5

Training Loss: 1.4401744716587959
Validation_loss: 1.4396090539878206
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 6

Training Loss: 1.440219045672932
Validation_loss: 1.439524548024889
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 7

Training Loss: 1.4401194870468186
Validation_loss: 1.4398169304115573
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 8

Training Loss: 1.4402725464221324
Validation_loss: 1.4395026141137695
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Epoch 9

Training Loss: 1.4401697135436002
Validation_loss: 1.4398159408477853
Accuracy: 0.4524793388429752
Macro F1: 0.06922712185870081

Best F1 score: 0.06922712185870081 at epoch 0

In [37]:
print("Learning rate:", best_learning_rate)

Learning rate: 0.001

Tuning for best learning rate:

In [29]:
import copy
initial_model_state = copy.deepcopy(model_splice.state_dict())

learning_rate = [0.0001, 0.001, 0.01]
best_f1_score = -1
best_learning_rate = 0

for lr in learning_rate:
    print(f"Testing learning rate: {lr}")

    # resettign CNN
    model_splice.load_state_dict(initial_model_state)
    optimizer_splice = torch.optim.Adam(model_splice.parameters(), lr = lr)
    best_model_for_lr = -1

    for epoch in range(3):
        train_loss = train_loop(train_loader_splice, model_splice, loss_fn, optimizer_splice, device)

        # Validate
        val_loss, val_accuracy, val_f1 = evaluate_loop(val_loader_splice, model_splice, loss_fn, device)
        print(f"\nEpoch {epoch}")
        print(f"Training Loss: {train_loss}\nValidation_loss: {val_loss}\
                \nAccuracy: {val_accuracy}\nMacro F1: {val_f1}\n")

        # Save the model if it has the best F1 score so far
        if val_f1 > best_f1_score: 
            best_model_for_lr = val_f1
    print(f"Best F1 score for learning rate {lr}: {best_model_for_lr}")
    if best_model_for_lr > best_f1_score:
        best_f1_score = best_model_for_lr
        best_learning_rate = lr

Testing learning rate: 0.0001

Epoch 0
Training Loss: 1.0393774240902065
Validation_loss: 1.021743546220548
Accuracy: 0.5188284518828452
Macro F1: 0.22773186409550047


Epoch 1
Training Loss: 1.023174589544041
Validation_loss: 1.0150662118171547
Accuracy: 0.5188284518828452
Macro F1: 0.22773186409550047


Epoch 2
Training Loss: 1.0135668129249373
Validation_loss: 1.0075116916929827
Accuracy: 0.5188284518828452
Macro F1: 0.22773186409550047

Best F1 score for learning rate 0.0001: 0.22773186409550047
Testing learning rate: 0.001

Epoch 0
Training Loss: 1.0058683942931679
Validation_loss: 0.9167146053648394
Accuracy: 0.5251046025104602
Macro F1: 0.2564234607492022


Epoch 1
Training Loss: 0.8814841887033205
Validation_loss: 0.8179802651435262
Accuracy: 0.5941422594142259
Macro F1: 0.43427761702330353


Epoch 2
Training Loss: 0.841128210481665
Validation_loss: 0.7793377321135548
Accuracy: 0.6422594142259415
Macro F1: 0.6276473423013708

Best F1 score for learning rate 0.001: 0.6276473423013708
Testing learning rate: 0.01

Epoch 0
Training Loss: 1.039360275970037
Validation_loss: 1.0266110158864423
Accuracy: 0.5188284518828452
Macro F1: 0.22773186409550047


Epoch 1
Training Loss: 1.0271006394703186
Validation_loss: 1.0350828599730295
Accuracy: 0.5188284518828452
Macro F1: 0.22773186409550047


Epoch 2
Training Loss: 1.030039043128624
Validation_loss: 1.0276251986435767
Accuracy: 0.5188284518828452
Macro F1: 0.22773186409550047

Best F1 score for learning rate 0.01: -1

Further tuning with the best learning rate

In [30]:
best_f1_score = -1
best_epoch = 0
best_model_state = None
model_splice.load_state_dict(initial_model_state)

# Initializing Optimizer
optimizer_splice = torch.optim.Adam(model_splice.parameters(), lr = best_learning_rate) 

for epoch in range(10):
    train_loss = train_loop(train_loader_splice, model_splice, loss_fn, optimizer_splice, device)

    # Validate
    val_loss, val_accuracy, val_f1 = evaluate_loop(
        val_loader_splice, model_splice, loss_fn, device
    )
    print(f"Epoch {epoch}\n")
    print(f"Training Loss: {train_loss}\nValidation_loss: {val_loss}\
            \nAccuracy: {val_accuracy}\nMacro F1: {val_f1}\n")

    # Save the model if it has the best F1 score so far
    if val_f1 > best_f1_score: 
        best_f1_score = val_f1
        best_epoch = epoch
        best_model_state = model_splice.state_dict()

print(f"Best F1 score: {best_f1_score} at epoch {best_epoch}")
model_splice.load_state_dict(best_model_state)

Epoch 0

Training Loss: 1.0094234111380587
Validation_loss: 0.9515819024590768
Accuracy: 0.5313807531380753
Macro F1: 0.27682088597560506

Epoch 1

Training Loss: 0.9019310958900368
Validation_loss: 0.8224404681177817
Accuracy: 0.6150627615062761
Macro F1: 0.5271849189435627

Epoch 2

Training Loss: 0.8577505309223141
Validation_loss: 0.799172774549558
Accuracy: 0.6443514644351465
Macro F1: 0.5691703422630655

Epoch 3

Training Loss: 0.8179571251762364
Validation_loss: 0.7835711130880162
Accuracy: 0.6171548117154811
Macro F1: 0.5244331655794744

Epoch 4

Training Loss: 0.8233806618776688
Validation_loss: 0.781331933193127
Accuracy: 0.6569037656903766
Macro F1: 0.5919558996819547

Epoch 5

Training Loss: 0.8093989760682915
Validation_loss: 0.7662282950209773
Accuracy: 0.6234309623430963
Macro F1: 0.5422045916022733

Epoch 6

Training Loss: 0.800392691555662
Validation_loss: 0.7452391939214333
Accuracy: 0.6736401673640168
Macro F1: 0.6443754664280806

Epoch 7

Training Loss: 0.8046078554355025
Validation_loss: 0.7639625970445667
Accuracy: 0.6213389121338913
Macro F1: 0.5230109041214143

Epoch 8

Training Loss: 0.7878976508504154
Validation_loss: 0.745836146643471
Accuracy: 0.6527196652719666
Macro F1: 0.6160061103350293

Epoch 9

Training Loss: 0.7943968169086275
Validation_loss: 0.7891439606112167
Accuracy: 0.606694560669456
Macro F1: 0.4922471743622599

Best F1 score: 0.6443754664280806 at epoch 6

DNA 3-mer TF-IDF Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

# Creating a TF-IDF representation based on character 3-mers
DNA_tfidf = TfidfVectorizer(analyzer='char', ngram_range=(3, 3), lowercase=False) 

X_train_DNA_tf = DNA_tfidf.fit_transform(X_train_DNA.astype(str))
X_val_DNA_tf = DNA_tfidf.transform(X_val_DNA.astype(str))
X_test_DNA_tf = DNA_tfidf.transform(X_test_DNA.astype(str))

# Logistic Regression
DNA_lr = LogisticRegression(max_iter = 1000, random_state = 22)
DNA_lr.fit(X_train_DNA_tf, Y_train_DNA)
Y_val_pred_DNA = DNA_lr.predict(X_val_DNA_tf)

Splice 3-mer TF-IDF Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

# Creating a TF-IDF representation based on character 3-mers
splice_tfidf = TfidfVectorizer(analyzer='char', ngram_range=(3, 3), lowercase=False) 

X_train_splice_tf = splice_tfidf.fit_transform(X_train_splice.astype(str))
X_val_splice_tf = splice_tfidf.transform(X_val_splice.astype(str))
X_test_splice_tf = splice_tfidf.transform(X_test_splice.astype(str))

# Logistic Regression
splice_lr = LogisticRegression(max_iter = 1000, random_state = 22)
splice_lr.fit(X_train_splice_tf, Y_train_splice)
Y_val_pred_splice = splice_lr.predict(X_val_splice_tf)

In [33]:
# Under log regression line
from sklearn.model_selection import GridSearchCV


DNA_grid = GridSearchCV(DNA_lr, param_grid = {'C':[0.01, 0.1, 1, 10, 100], 'class_weight':[None, 'balanced']}, cv=5, scoring='f1_macro')
DNA_grid.fit(X_train_DNA_tf, Y_train_DNA)
print(f'Best parameters: {DNA_grid.best_params_}')
print(f'Best cross-validation macro F1 score: {DNA_grid.best_score_}')

best_DNA_lr = DNA_grid.best_estimator_

# https://scikit-learn.org/1.3/tutorial/statistical_inference/model_selection.html

Best parameters: {'C': 100, 'class_weight': None}
Best cross-validation macro F1 score: 0.5658959192248825

In [34]:
# Testing the model on the test set
Y_test_pred_DNA = best_DNA_lr.predict(X_test_DNA_tf)
print(f'Test Accuracy: {accuracy_score(Y_test_DNA, Y_test_pred_DNA)}')
print(f'Test Macro F1: {f1_score(Y_test_DNA, Y_test_pred_DNA, average="macro")}')

Test Accuracy: 0.6810268515786367
Test Macro F1: 0.5680402024253408

In [35]:
# Under log regression line

splice_grid = GridSearchCV(splice_lr, param_grid = {'C':[0.01, 0.1, 1, 10, 100]}, cv=5, scoring='f1_macro')
splice_grid.fit(X_train_splice_tf, Y_train_splice)
print(f'Best parameters: {splice_grid.best_params_}')
print(f'Best cross-validation macro F1 score: {splice_grid.best_score_}')

best_splice_lr = splice_grid.best_estimator_

Best parameters: {'C': 100}
Best cross-validation macro F1 score: 0.6010344081128078

In [36]:
# Testing the model on the test set
Y_test_pred_splice = best_splice_lr.predict(X_test_splice_tf)
print(f'Test Accuracy: {accuracy_score(Y_test_splice, Y_test_pred_splice)}')
print(f'Test Macro F1: {f1_score(Y_test_splice, Y_test_pred_splice, average="macro")}')

Test Accuracy: 0.6116910229645094
Test Macro F1: 0.5750358874790459

### Saving outputs
Save the count vector representation as per spectification.

## Summary
Give a short summary and anything you would like to talk about the assessment tasks here.

## References

# I think try changing grouping for DNA